function [ tracks, fe, musiques ] = get_tracks
% OUTPUTS : - tracks : matrice m*n contenant n pistes de m échantillons
%           - fe : fréquence d'échantillonnage
%           - musiques : cellule contenant le nom des pistes audio

musiques = { ...
    'acoustik_gtr.wav'; ...
    'bass.wav'; ...
    'cello.wav'; ...
    'drums.wav'; ...
    'elec_gtrs.wav'; ...
    'lead_vocal.wav'; ...
    'piano.wav'; ...
    'voix_harmo1.wav'; ...
    'voic_harmo2.wav'; ...
    'sunrise-Mix_Bal_Pan.wav'};

[audio, fe] = audioread(musiques{1});
tracks = zeros(size(audio,1), numel(musiques));

h = waitbar(0,'Chargement de la musique');
for ind = 1:numel(musiques)
    tracks(:,ind) = mean(audioread(musiques{ind}),2);
    waitbar(ind/numel(musiques));
end
delete(h)
